### ISSUE TITLE
Missing file: `testing_task_for_info_gain_patterns`

### ISSUE THREAD

**Issue by wxl1999** [nouhadziri/faith-and-fate#2]
Hi, I read your awesome work and tried to run your code, but found a missing file `testing_task_for_info_gain_patterns.py`, which is imported and used in the file `dynamic_programming/generate_training_data.py`. Hope you can provide this file. Thanks!

**Comment by nouhadziri** [comment]
Hello,

I haven't received any notification of this issue in my email, and upon investigation, it seems that it was redirected to the spam folder. Sorry for the inconvenience and thank you for bringing this to my attention via email. I have updated the code and add the `testing_task_for_info_gain_patterns.py` script. 
Hope this helps.

Thanks!

**Comment by nouhadziri** [comment]
Issue fixed.
